### ISSUE TITLE
problem getting started

### ISSUE THREAD

**Issue by jave** [KeyWeeUsr/emacs-syncthing#2]
I'm having some probems getting started.
I customized the server token, but the syncthing buffer is just empty.

**Comment by KeyWeeUsr** [comment]
@jave Unfortunate but unless `syncthing--ping` failed which you should see an error for in `*Messages*` (<kbd>C</kbd>-<kbd>h</kbd> <kbd>e</kbd>) the token works fine and it's more of an unhandled data in the code, most likely some bad `nil` for a func that doesn't accept it.

You can first try to: <kbd>M</kbd>-<kbd>x</kbd> `toggle-debug-on-error` and see if it crashes somewhere. If yes, please paste the log here.

If that doesn't help I added debugging logs for such case in https://github.com/KeyWeeUsr/emacs-syncthing/commit/9ab5e9dca082a9b9b3bbc311928af9fca1e2cf5c. You can enable it with <kbd>M</kbd>-<kbd>x</kbd> `customize-variable` `syncthing-debug` or `(setq syncthing-debug t)`.

Then you should be able to pinpoint the issue by going through `*Messages*`. Feel free to paste the log here if you want however it might include data you might not want to share publicly such as non-LAN IPs, tokens, folder names, etc. Those you might want to filter out.

If long lines cause troubles on your side, use `so-long-mode` or `so-long-minor-mode`.

**Comment by progfolio** [comment]
Same issue here.
Stepping through the `syncthing` command with edebug shows this error:

```
Contacting host: 127.0.0.1:8384
File error: "https://127.0.0.1:8384/rest/system/ping", "Forbidden"
```

So the API is rejecting that call.
You will want to add some error handling for such cases (usually via `condition-case`).

**Comment by KeyWeeUsr** [comment]
@progfolio Am I missing something? The `condition-case-unless-debug` is present here: https://github.com/KeyWeeUsr/emacs-syncthing/blob/9ab5e9dca082a9b9b3bbc311928af9fca1e2cf5c/syncthing.el#L428

**Comment by progfolio** [comment]
I'd have to look over the whole control flow. Perhaps the call is wrapped elsewhere in a way that prevents the error from being signaled.

**Comment by KeyWeeUsr** [comment]
I think I found the bug and rather nasty behavior of `cl-defstruct`. The bug was non-nil `unless` entered with `""` (empty string) hence no `(user-error)` call on the empty token. Then the `cl-defstruct` instance created and pinned - with an empty token - so even if it were set later on, the instance would still contain `""` and silently fail with an empty buffer.

Also for some reason I thought `customize-variable` is a blocking call but that was just having `nil` as token default not triggering `(pop-to-buffer)` call and test having that branch mocked out. [diff](https://github.com/KeyWeeUsr/emacs-syncthing/compare/1.4.1..1.4.2) Oh well.

@jave Try checking with `1.4.2` whether you still experience the same behavior.

**Comment by progfolio** [comment]
Peter Badida ***@***.***> writes:

> I think I found the bug and rather nasty behavior of 
> cl-defstruct. The bug was non-nil
> unless entered with "" (empty string) hence no (user-error) call 
> on the empty token. Then
> the cl-defstruct instance created and pinned - with an empty 
> token - so even if it were set
> later on, the instance would still contain "" and silently fail 
> with an empty buffer.

That's not so much the behavior of cl-defstruct.
e.g. Calling `syncthing--server` with no args will initialize 
every slot with nil unless you specify a default in the struct's 
definition.
 
> Also for some reason I thought customize-variable is a blocking 
> call but that was just
> having nil as token default not triggering (pop-to-buffer) call 
> and test having that branch
> mocked out. diff Oh well.

customize-variable is overkill in this case.
Signaling a descriptive user-error should be enough.

**Comment by jave** [comment]
it works for me now, thanks!

I agree with @progfolio that customizing the variable automatically when its not set is more confusing than helpful. In my case the customize buffer got buried somewhere so I didnt see it.

**Comment by KeyWeeUsr** [comment]
Glad to hear that! Closing :v:

Also, the buffer got buried because of the incorrect code path. It should have either blocked until the token was put there or not launch the new buffer, so for you that was basically both - opening customize buffer and opening the Syncthing buffer on top of it which failed to do anything due to using empty/invalid token.

As for the initial token input via customize buffer, the idea behind that is to be as straightforward as possible for a new user or especially [a non-programmer](https://www.youtube.com/watch?v=FtieBc3KptU). Customize seems to be a nicer approach than a tiny line in the mini-buffer with `(read-string ...)` for the initial approach. For something where user would know a bit more, such as custom host/port I kept it just for `(syncthing-with-base)` and `(read-string)`.
