### ISSUE TITLE
Icons don't show

### ISSUE THREAD

**Issue by Igor1257** [KeyWeeUsr/emacs-syncthing#5]
![image](https://github.com/KeyWeeUsr/emacs-syncthing/assets/23632788/0ddd9615-e562-407d-8482-386c8067fed6)

![image](https://github.com/KeyWeeUsr/emacs-syncthing/assets/23632788/120a9eb2-e414-4c02-ae5f-a1619d8d9c34)

on Windows 10
GNU Emacs 29.1 (build 2, x86_64-w64-mingw32) of 2024-01-02

**Comment by KeyWeeUsr** [comment]
@Igor1257 What font do you use in that buffer (or in Emacs overall)?

**Comment by Igor1257** [comment]
Oh, thanks.
I set
(set-face-attribute 'default nil :family "Hack Nerd Font" :height 100)

and now looks better

![image](https://github.com/KeyWeeUsr/emacs-syncthing/assets/23632788/fa98552f-c48c-4cd9-bdc5-c129b2a335a2)

**Comment by Igor1257** [comment]
@KeyWeeUsr please suggest which font is preferred.

**Comment by KeyWeeUsr** [comment]
@Igor1257 `/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf` is the default font I've been using on multiple Linux boxes because it's been simply set as the default for monospace font.
Although it seems to work fine for all of the icons it might be useful to add a customization value which would strip all of the icons or even allow setting up custom ones :thinking:

**Comment by KeyWeeUsr** [comment]
Solved in [`2.3.0`](https://github.com/KeyWeeUsr/emacs-syncthing/releases/tag/2.3.0) by providing both ASCII mode and support for themes where icons can be chosen from:
1. [list of themes](https://github.com/KeyWeeUsr/emacs-syncthing/blob/725b2dac739c6dd03db0a03f49f3c1cbf9b336bd/syncthing-themes.el#L128)
2. [custom theme](https://github.com/KeyWeeUsr/emacs-syncthing/blob/725b2dac739c6dd03db0a03f49f3c1cbf9b336bd/syncthing-themes.el#L37) implemented as per the examples below the default one.

**Comment by Knusper** [comment]
Please reconsider reopening the bug.  Even the current themes, and especially the default theme, use symbols from the Private Use Area of the Unicode table.  Depending on the font in use (also in the terminal), this can result in quite messy output.

**Comment by KeyWeeUsr** [comment]
@Knusper Hmmm, do you have a set of symbols that are working for you? :thinking: I could add it as a new theme, perhaps set as the default if it's applicable to more fonts?
Otherwise I'm unsure how would you like to solve this problem except by either using pure ASCII or having an own theme where you specify what works for you (or replace the symbols in a theme with `""`) since there will always be differences between fonts no matter the symbol I use.

**Comment by Knusper** [comment]
How about using the `all-the-icons` package in emacs.  In non-graphical emacs one needs then to support only UTF-8 symbols outside the private use area of the unicode block. These are standardized amongst different unicode fonts. A different solution might be to require a specific font family for the buffers in graphical buffers.

**Comment by KeyWeeUsr** [comment]
@Knusper 👋 I added a new theme using All The Icons. Feel free to give it a try. https://github.com/KeyWeeUsr/emacs-syncthing/blob/9c69be95d3979cd4aa15896206fa69d8465039ae/syncthing-themes.el#L132
